module Blinker.Blinker (topEntity) where

-- The configuration of this project automatically hides the implicit prelude
-- and enables a bunch of necessary language extension for Clash to work.
-- Clash provides it's own Prelude containing a lot of useful stuff for us to
-- explore.
import Clash.Prelude

-- processLED describes a transition within a `mealy` automaton. Clash enables
-- us to divide the description of our hardware and implmentation into separate
-- steps leading to (hopefully) better understandable code.
--
-- The type-signature for processLED can be written like this:
--
--  processLED :: s -> i -> (s,o)
--      where s = State
--            i = Input
--            o = Output
--
-- Recall that we are really just describing how our mealy machine will
-- transition.
--
-- What is this `Index 100000001` you might wonder. The Arty A7-35T runs with a
-- clock of 100MHz. To let our LED turn on and off in a one second interval, we
-- can use an accumulator which overflows every 100000000 == 100*10^6 time we
-- add one to it.
-- (Note, this is not the best way of implementing it but at least very easy,
-- which is our goal right now)
--
-- Clash provides us with the ability to define arbitrary bounded unsigned
-- integers via `Index n`. Thus what we are describing here is an integer
-- which does exactly what we talked about in the paragraph above.
--
-- acc and led are our current machine state.
-- acc' and led' are our updated machine state.
-- led' is also used as the OUTPUT of our machine. What happens is, that Clash
-- will use this output as a `Signal` which turns the power of the LED ON or
-- OFF. We obviously only need one bit to represent the ON or OFF state, thus
-- we also use the Clash provided `Bit` type.
--
-- The input `a` here is polymorphic. We will just plug the `Clock` in as the
-- input and ignore the input here. This basically means each rising edge of
-- our clock will lead to a state transition, thus incrementing our
-- accumulator and possibly flipping the state of our `led`.
processLED :: (Index 100000001, Bit) -> a -> ((Index 100000001, Bit), Bit)
processLED (acc, led) _ = ((acc', led'), led')
    where
        acc' = acc + 1
        led' | acc == 0 = complement led
             | otherwise = led


-- What follows here is an `Annotation`. The annotation is not necessary for
-- this project to work BUT it will greatly ease what we have to do in the next
-- step.
-- The `topEntity` will be used as Clash's "main" entry point. This is default
-- behaviour.
--
-- t_name = "helloworld" tells Clash how to name the entity in the generated
-- VHDL/Verilog.
--
-- t_inputs = Allows us to define HOW the inputs of our generated module are
-- named. Here we say that we expect our module to have at least one input
-- named "clk". (Note that Clash will add inputs with autogenerated names, when
-- it determines that our module does use more than specified. In this case the
-- naming SEEMS to be in the order of the described list.
--
-- t_output = Allows us to define HOW the output of our generated module is
-- named. Simply "led" here.
{-# ANN topEntity
    (Synthesize
        { t_name = "helloworld"
        , t_inputs = [ PortName "clk" ]
        , t_output = PortName "led"
        }) #-}
-- Most of the stuff works in some kind of `Domain`. Since we are using Vivado,
-- which in the end is just a Xilinx system, we can use the clash defined
-- Domain = XilinxSystem.
-- The XilinxSystem defines a clock which is per default 100MHz, which is why
-- we do not have more to do. IF your FPGA has a different clock, you would
-- need to create a custom `Domain` which in turn describes a Clock with the
-- right frequency. Then you would need to use `Clock MyDomain -> Signal
-- MyDomain -- Bit` here.
--
-- The implementation of our circuit is pretty straight forward:
topEntity :: Clock XilinxSystem -> Signal XilinxSystem Bit
topEntity clk = exposeClockResetEnable (mealy processLED (0, 0) (pure clk)) clk rst en
    where
          -- `ledMachine = mealy processLED (0, 0) (pure clk)`:
          -- ledMachine uses our mealy transition function `processLED` with
          -- the initial state `(0, 0)` and the input `(pure clk)` to create a
          -- mealy machine.
          -- `clk` itself is the input to our defined hardware module. `clk` is
          -- of type `Clock XilinxSystem`, but the mealy machine requires the
          -- input to be a `Signal`, which already indicates that we are
          -- describing a sequential circuit. So to tell that we are indeed
          -- using the clock as an input, we have to "lift" `clk` to be a
          -- `Signal XilinxSystem (Clock XilinxSystem)`. This is enough for
          -- Clash to infer, that we are indeed using the given clock as an
          -- input for our defined mealy transition function.

          -- Every mealy machine is defined to accept a `Clock`, `Reset` and
          -- `Enable`. This makes sense, but it took me way to long to figure
          -- out how to tell Clash that I do not care about `Reset` and
          -- `Enable` in my described component. Clash ALWAYS implicitly routes
          -- `Clock`, `Reset` and `Enable` to your defined components and I did
          -- not want to pollute the component by extending the `topEntity` to
          -- also accept `Reset XilinxSystem` and `Enable XilinxSystem` because
          -- this would require us to EXPLICITLY define more inputs for our
          -- Bitstream generation to work, more on that later.
          rst = resetGen

          -- We also just want our component to be always active and act on the
          -- clock input signal.
          en = enableGen

          -- `exposeClockResetEnable ledMachine clk rst en`:
          -- exposeClockResetEnable allows us to expose the hidden `Clock`,
          -- `Reset` and `Enable` within `ledMachine`. Remember, this is
          -- because every mealy machine is defined to have a hidden `Clock`,
          -- `Reset` and `Enable`. We would not need this if our input to our
          -- `ledMachine` would not explicitly take in the `Clock`, but since
          -- it does, we have to do some plumbing here.
